/**
 * Resolve the `SKILL.md` behind a catalogue entry, for the skills this repo owns.
 *
 * Split out of `render.ts` for two reasons. It touches the filesystem, and the
 * renderer's whole value is that a captured payload can be re-rendered later
 * without re-running pi — which stops being true the moment rendering depends
 * on files that may have moved. And ownership is a policy question, not a
 * presentation one: it belongs where it can be tested on its own.
 *
 * Ownership is decided by where the file really lives, after following the
 * symlink, because that is the only thing that distinguishes ours from a
 * third party's. `~/.pi/agent/skills/` holds both — our checkouts are linked
 * in beside skills from elsewhere, and the link's location says nothing about
 * who wrote the target.
 *
 * Ours means one of:
 *
 * - inside this checkout (`skills/<name>/SKILL.md`), or
 * - generated by one of our extensions at startup
 *   (`~/.pi/agent/generated-skills/`), which is the case that motivated this:
 *   the `subagents` skill is written to be read, and it exists nowhere a
 *   reviewer would think to look.
 *
 * Everything else is deliberately skipped. A third-party skill's body is not
 * ours to review, and eighteen of them would bury the two that are.
 */

import { readFileSync, realpathSync } from "node:fs";
import { sep } from "node:path";
import { byteLength, type SkillBody } from "./render.ts";

/** Directory name an extension renders its skill into; not a path we own. */
const GENERATED = `${sep}generated-skills${sep}`;

export type Origin = "checked in" | "generated" | null;

/**
 * Which of ours this is, or `null` for a skill from elsewhere.
 *
 * Takes the already-resolved path so the decision is pure and the syscall
 * stays with the caller.
 */
export function ownerOf(realPath: string, repoRoot: string): Origin {
  if (realPath.includes(GENERATED)) return "generated";
  // The separator matters: a sibling checkout named `pi-setup-old` is not this
  // repo, and a prefix test alone would claim it.
  if (realPath.startsWith(repoRoot.endsWith(sep) ? repoRoot : repoRoot + sep))
    return "checked in";
  return null;
}

/**
 * Read the bodies of our skills, keyed by the location the catalogue advertised.
 *
 * Keyed by the advertised path rather than the resolved one so the renderer can
 * look an entry up with exactly the string it parsed out of the prompt.
 *
 * Unreadable is not an error. A skill may be linked from somewhere that has
 * since moved, and a report that refuses to render over one dangling symlink
 * is worse than a report with one body missing.
 */
export function readSkillBodies(
  locations: ReadonlyArray<string>,
  repoRoot: string,
): Record<string, SkillBody> {
  const bodies: Record<string, SkillBody> = {};
  for (const location of locations) {
    try {
      const real = realpathSync(location);
      const origin = ownerOf(real, repoRoot);
      if (!origin) continue;
      const text = readFileSync(real, "utf8");
      bodies[location] = { text, bytes: byteLength(text), origin };
    } catch {
      // Dangling link, permissions, a path that no longer exists — skip it.
    }
  }
  return bodies;
}
